// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class User;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserRoot : GPBRootObject
@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_Id_p = 1,
  User_FieldNumber_Name = 2,
  User_FieldNumber_Avatar = 3,
  User_FieldNumber_Address = 4,
  User_FieldNumber_Mobile = 5,
  User_FieldNumber_Ext = 6,
};

@interface User : GPBMessage

/** 主键id */
@property(nonatomic, readwrite) int64_t id_p;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

/** 手机号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 扩展信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *ext;
/** The number of items in @c ext without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ext_Count;

@end

#pragma mark - UserList

typedef GPB_ENUM(UserList_FieldNumber) {
  UserList_FieldNumber_ListArray = 1,
  UserList_FieldNumber_Page = 2,
  UserList_FieldNumber_Limit = 3,
};

@interface UserList : GPBMessage

/** 用户列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<User*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

/** 分页 */
@property(nonatomic, readwrite) int32_t page;

/** 分页条数 */
@property(nonatomic, readwrite) int32_t limit;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
