// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package Sample.Model;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sample.Model.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *主键id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    java.lang.String getMobile();
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    int getExtCount();
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    boolean containsExt(
        java.lang.String key);
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExt();
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtMap();
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    java.lang.String getExtOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    java.lang.String getExtOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Sample.Model.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Sample.Model.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      avatar_ = "";
      address_ = "";
      mobile_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ext_ = com.google.protobuf.MapField.newMapField(
                    ExtDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              ext__ = input.readMessage(
                  ExtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              ext_.getMutableMap().put(
                  ext__.getKey(), ext__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.Model.UserOuterClass.internal_static_Sample_Model_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.Model.UserOuterClass.internal_static_Sample_Model_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sample.Model.UserOuterClass.User.class, Sample.Model.UserOuterClass.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *主键id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 5;
    private volatile java.lang.Object mobile_;
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXT_FIELD_NUMBER = 6;
    private static final class ExtDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  Sample.Model.UserOuterClass.internal_static_Sample_Model_User_ExtEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ext_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExt() {
      if (ext_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      return ext_;
    }

    public int getExtCount() {
      return internalGetExt().getMap().size();
    }
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public boolean containsExt(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExt() {
      return getExtMap();
    }
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
      return internalGetExt().getMap();
    }
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public java.lang.String getExtOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public java.lang.String getExtOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mobile_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExt(),
          ExtDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mobile_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExt().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        ext__ = ExtDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, ext__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Sample.Model.UserOuterClass.User)) {
        return super.equals(obj);
      }
      Sample.Model.UserOuterClass.User other = (Sample.Model.UserOuterClass.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getAvatar()
          .equals(other.getAvatar())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getMobile()
          .equals(other.getMobile())) return false;
      if (!internalGetExt().equals(
          other.internalGetExt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      if (!internalGetExt().getMap().isEmpty()) {
        hash = (37 * hash) + EXT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Sample.Model.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Sample.Model.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sample.Model.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sample.Model.User)
        Sample.Model.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetExt();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableExt();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sample.Model.UserOuterClass.User.class, Sample.Model.UserOuterClass.User.Builder.class);
      }

      // Construct using Sample.Model.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        avatar_ = "";

        address_ = "";

        mobile_ = "";

        internalGetMutableExt().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_User_descriptor;
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.User getDefaultInstanceForType() {
        return Sample.Model.UserOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.User build() {
        Sample.Model.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.User buildPartial() {
        Sample.Model.UserOuterClass.User result = new Sample.Model.UserOuterClass.User(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.avatar_ = avatar_;
        result.address_ = address_;
        result.mobile_ = mobile_;
        result.ext_ = internalGetExt();
        result.ext_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sample.Model.UserOuterClass.User) {
          return mergeFrom((Sample.Model.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sample.Model.UserOuterClass.User other) {
        if (other == Sample.Model.UserOuterClass.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        internalGetMutableExt().mergeFrom(
            other.internalGetExt());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sample.Model.UserOuterClass.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sample.Model.UserOuterClass.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 5;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 5;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 5;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 5;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> ext_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetExt() {
        if (ext_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtDefaultEntryHolder.defaultEntry);
        }
        return ext_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableExt() {
        onChanged();;
        if (ext_ == null) {
          ext_ = com.google.protobuf.MapField.newMapField(
              ExtDefaultEntryHolder.defaultEntry);
        }
        if (!ext_.isMutable()) {
          ext_ = ext_.copy();
        }
        return ext_;
      }

      public int getExtCount() {
        return internalGetExt().getMap().size();
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public boolean containsExt(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetExt().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExt() {
        return getExtMap();
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
        return internalGetExt().getMap();
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public java.lang.String getExtOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExt().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public java.lang.String getExtOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExt().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExt() {
        internalGetMutableExt().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public Builder removeExt(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExt().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableExt() {
        return internalGetMutableExt().getMutableMap();
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */
      public Builder putExt(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExt().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *扩展信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; ext = 6;</code>
       */

      public Builder putAllExt(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExt().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Sample.Model.User)
    }

    // @@protoc_insertion_point(class_scope:Sample.Model.User)
    private static final Sample.Model.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Sample.Model.UserOuterClass.User();
    }

    public static Sample.Model.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Sample.Model.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sample.Model.UserList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    java.util.List<Sample.Model.UserOuterClass.User> 
        getListList();
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    Sample.Model.UserOuterClass.User getList(int index);
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    int getListCount();
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    java.util.List<? extends Sample.Model.UserOuterClass.UserOrBuilder> 
        getListOrBuilderList();
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    Sample.Model.UserOuterClass.UserOrBuilder getListOrBuilder(
        int index);

    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>int32 page = 2;</code>
     */
    int getPage();

    /**
     * <pre>
     *分页条数
     * </pre>
     *
     * <code>int32 limit = 3;</code>
     */
    int getLimit();
  }
  /**
   * Protobuf type {@code Sample.Model.UserList}
   */
  public  static final class UserList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Sample.Model.UserList)
      UserListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserList.newBuilder() to construct.
    private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<Sample.Model.UserOuterClass.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(Sample.Model.UserOuterClass.User.parser(), extensionRegistry));
              break;
            }
            case 16: {

              page_ = input.readInt32();
              break;
            }
            case 24: {

              limit_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.Model.UserOuterClass.internal_static_Sample_Model_UserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.Model.UserOuterClass.internal_static_Sample_Model_UserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sample.Model.UserOuterClass.UserList.class, Sample.Model.UserOuterClass.UserList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<Sample.Model.UserOuterClass.User> list_;
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public java.util.List<Sample.Model.UserOuterClass.User> getListList() {
      return list_;
    }
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public java.util.List<? extends Sample.Model.UserOuterClass.UserOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public Sample.Model.UserOuterClass.User getList(int index) {
      return list_.get(index);
    }
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public Sample.Model.UserOuterClass.UserOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int LIMIT_FIELD_NUMBER = 3;
    private int limit_;
    /**
     * <pre>
     *分页条数
     * </pre>
     *
     * <code>int32 limit = 3;</code>
     */
    public int getLimit() {
      return limit_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      if (page_ != 0) {
        output.writeInt32(2, page_);
      }
      if (limit_ != 0) {
        output.writeInt32(3, limit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, limit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Sample.Model.UserOuterClass.UserList)) {
        return super.equals(obj);
      }
      Sample.Model.UserOuterClass.UserList other = (Sample.Model.UserOuterClass.UserList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (getPage()
          != other.getPage()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Sample.Model.UserOuterClass.UserList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.UserList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.UserList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample.Model.UserOuterClass.UserList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Sample.Model.UserOuterClass.UserList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sample.Model.UserList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sample.Model.UserList)
        Sample.Model.UserOuterClass.UserListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_UserList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_UserList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sample.Model.UserOuterClass.UserList.class, Sample.Model.UserOuterClass.UserList.Builder.class);
      }

      // Construct using Sample.Model.UserOuterClass.UserList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        page_ = 0;

        limit_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sample.Model.UserOuterClass.internal_static_Sample_Model_UserList_descriptor;
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.UserList getDefaultInstanceForType() {
        return Sample.Model.UserOuterClass.UserList.getDefaultInstance();
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.UserList build() {
        Sample.Model.UserOuterClass.UserList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Sample.Model.UserOuterClass.UserList buildPartial() {
        Sample.Model.UserOuterClass.UserList result = new Sample.Model.UserOuterClass.UserList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.page_ = page_;
        result.limit_ = limit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sample.Model.UserOuterClass.UserList) {
          return mergeFrom((Sample.Model.UserOuterClass.UserList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sample.Model.UserOuterClass.UserList other) {
        if (other == Sample.Model.UserOuterClass.UserList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sample.Model.UserOuterClass.UserList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sample.Model.UserOuterClass.UserList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Sample.Model.UserOuterClass.User> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<Sample.Model.UserOuterClass.User>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Sample.Model.UserOuterClass.User, Sample.Model.UserOuterClass.User.Builder, Sample.Model.UserOuterClass.UserOrBuilder> listBuilder_;

      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public java.util.List<Sample.Model.UserOuterClass.User> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Sample.Model.UserOuterClass.User getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder setList(
          int index, Sample.Model.UserOuterClass.User value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder setList(
          int index, Sample.Model.UserOuterClass.User.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder addList(Sample.Model.UserOuterClass.User value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder addList(
          int index, Sample.Model.UserOuterClass.User value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder addList(
          Sample.Model.UserOuterClass.User.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder addList(
          int index, Sample.Model.UserOuterClass.User.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends Sample.Model.UserOuterClass.User> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Sample.Model.UserOuterClass.User.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Sample.Model.UserOuterClass.UserOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public java.util.List<? extends Sample.Model.UserOuterClass.UserOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Sample.Model.UserOuterClass.User.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            Sample.Model.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public Sample.Model.UserOuterClass.User.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, Sample.Model.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <pre>
       *用户列表
       * </pre>
       *
       * <code>repeated .Sample.Model.User list = 1;</code>
       */
      public java.util.List<Sample.Model.UserOuterClass.User.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Sample.Model.UserOuterClass.User, Sample.Model.UserOuterClass.User.Builder, Sample.Model.UserOuterClass.UserOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Sample.Model.UserOuterClass.User, Sample.Model.UserOuterClass.User.Builder, Sample.Model.UserOuterClass.UserOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      private int page_ ;
      /**
       * <pre>
       *分页
       * </pre>
       *
       * <code>int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <pre>
       *分页
       * </pre>
       *
       * <code>int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分页
       * </pre>
       *
       * <code>int32 page = 2;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <pre>
       *分页条数
       * </pre>
       *
       * <code>int32 limit = 3;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       *分页条数
       * </pre>
       *
       * <code>int32 limit = 3;</code>
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分页条数
       * </pre>
       *
       * <code>int32 limit = 3;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Sample.Model.UserList)
    }

    // @@protoc_insertion_point(class_scope:Sample.Model.UserList)
    private static final Sample.Model.UserOuterClass.UserList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Sample.Model.UserOuterClass.UserList();
    }

    public static Sample.Model.UserOuterClass.UserList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserList>
        PARSER = new com.google.protobuf.AbstractParser<UserList>() {
      @java.lang.Override
      public UserList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Sample.Model.UserOuterClass.UserList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sample_Model_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sample_Model_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sample_Model_User_ExtEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sample_Model_User_ExtEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sample_Model_UserList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sample_Model_UserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\014Sample.Model\"\247\001\n\004User\022\n\n\002i" +
      "d\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\022\017\n" +
      "\007address\030\004 \001(\t\022\016\n\006mobile\030\005 \001(\t\022(\n\003ext\030\006 " +
      "\003(\0132\033.Sample.Model.User.ExtEntry\032*\n\010ExtE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"I\n\010" +
      "UserList\022 \n\004list\030\001 \003(\0132\022.Sample.Model.Us" +
      "er\022\014\n\004page\030\002 \001(\005\022\r\n\005limit\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Sample_Model_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sample_Model_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sample_Model_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Avatar", "Address", "Mobile", "Ext", });
    internal_static_Sample_Model_User_ExtEntry_descriptor =
      internal_static_Sample_Model_User_descriptor.getNestedTypes().get(0);
    internal_static_Sample_Model_User_ExtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sample_Model_User_ExtEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Sample_Model_UserList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Sample_Model_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sample_Model_UserList_descriptor,
        new java.lang.String[] { "List", "Page", "Limit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
